package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mariocampbell/vector/internal/config"
	"github.com/mariocampbell/vector/internal/updatecheck"
)

// seedContextRepo writes a minimal config + Go/Node repo so runContext can run.
func seedContextRepo(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	if err := config.Write(root, config.Resolve(root)); err != nil {
		t.Fatalf("write config: %v", err)
	}
	// Root go.mod so DetectBuildCmds (root-only) resolves Go build/test commands.
	writeContextFile(t, root, "go.mod", "module example.com/x\n\ngo 1.26\n")
	writeContextFile(t, root, "cmd/app/main.go", "package main\nfunc main() {}\n")
	writeContextFile(t, root, "web/package.json", `{"name":"web","main":"src/main.tsx"}`)
	writeContextFile(t, root, "web/src/main.tsx", "export {}\n")
	return root
}

func writeContextFile(t *testing.T, root, rel, content string) {
	t.Helper()
	abs := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", rel, err)
	}
}

// TestContextBackwardCompat verifies the no-flag output keeps the existing
// ContextOutput shape and gains only the additive intel field.
func TestContextBackwardCompat(t *testing.T) {
	root := seedContextRepo(t)
	out := captureStdout(t, func() error {
		return runContext([]string{"--repo-root", root, "--json"})
	})
	var co ContextOutput
	if err := json.Unmarshal([]byte(out), &co); err != nil {
		t.Fatalf("output not valid ContextOutput JSON: %v\n%s", err, out)
	}
	if co.Intel == nil {
		t.Fatal("expected additive intel field to be populated")
	}
	if co.Intel.Stack.Runtime.Name != "go" {
		t.Errorf("intel.stack.runtime = %+v, want go", co.Intel.Stack.Runtime)
	}
	// The cache must have been generated on read.
	if _, err := os.Stat(filepath.Join(root, ".vector", "cache", "fingerprints.json")); err != nil {
		t.Errorf("fingerprints.json not generated by vector context: %v", err)
	}
}

// TestContextForProjection covers the --for slices per tier and the unknown-command error.
func TestContextForProjection(t *testing.T) {
	root := seedContextRepo(t)

	t.Run("lazy tier (raw)", func(t *testing.T) {
		out := captureStdout(t, func() error {
			return runContext([]string{"--repo-root", root, "--json", "--for", "raw"})
		})
		var cs ContextSlice
		if err := json.Unmarshal([]byte(out), &cs); err != nil {
			t.Fatalf("invalid slice JSON: %v\n%s", err, out)
		}
		if cs.Command != "raw" || cs.Tier != "lazy-validate" {
			t.Errorf("command/tier = %s/%s, want raw/lazy-validate", cs.Command, cs.Tier)
		}
		if len(cs.ValidatedDomains) != 2 {
			t.Errorf("validatedDomains = %v, want [stack workspace]", cs.ValidatedDomains)
		}
		if cs.Stack == nil {
			t.Error("lazy slice missing stack summary")
		}
		if cs.BuildCmd != "" {
			t.Errorf("lazy slice should not carry buildCmd, got %q", cs.BuildCmd)
		}
	})

	t.Run("full tier (apply)", func(t *testing.T) {
		out := captureStdout(t, func() error {
			return runContext([]string{"--repo-root", root, "--json", "--for", "apply"})
		})
		var cs ContextSlice
		if err := json.Unmarshal([]byte(out), &cs); err != nil {
			t.Fatalf("invalid slice JSON: %v\n%s", err, out)
		}
		if cs.Tier != "full-validate" {
			t.Errorf("tier = %s, want full-validate", cs.Tier)
		}
		if cs.Stack == nil {
			t.Error("full slice missing stack summary")
		}
		if cs.TestCmd == "" {
			t.Error("full slice should carry testCmd (Go repo → go test)")
		}
	})

	t.Run("trust tier (status)", func(t *testing.T) {
		// Fresh root: prior subtests share `root` and would have created the cache.
		root := seedContextRepo(t)
		out := captureStdout(t, func() error {
			return runContext([]string{"--repo-root", root, "--json", "--for", "status"})
		})
		var cs ContextSlice
		if err := json.Unmarshal([]byte(out), &cs); err != nil {
			t.Fatalf("invalid slice JSON: %v\n%s", err, out)
		}
		if cs.Tier != "trust" {
			t.Errorf("tier = %s, want trust", cs.Tier)
		}
		if len(cs.ValidatedDomains) != 0 {
			t.Errorf("trust slice validatedDomains = %v, want empty", cs.ValidatedDomains)
		}
		if cs.Stack != nil || cs.ExamplePath != "" {
			t.Error("trust slice should carry no repo payload")
		}
		// Trust commands must not touch the cache.
		if _, err := os.Stat(filepath.Join(root, ".vector", "cache")); !os.IsNotExist(err) {
			t.Errorf("trust tier wrote cache dir (err=%v)", err)
		}
	})

	t.Run("unknown command errors", func(t *testing.T) {
		err := runContext([]string{"--repo-root", root, "--json", "--for", "nope"})
		if err == nil {
			t.Fatal("expected error for unknown --for command")
		}
	})
}

// TestContextWorktreeBlock verifies the additive worktree block: inert on a
// non-worktree repo (the default .vector store) and populated on a bare+worktree
// layout, with base/prefix defaults and overrides honored.
func TestContextWorktreeBlock(t *testing.T) {
	t.Run("non-worktree is inert", func(t *testing.T) {
		root := seedContextRepo(t) // config.Resolve → .vector/specs/<slug>/ (no [branch])
		out := captureStdout(t, func() error {
			return runContext([]string{"--repo-root", root, "--json"})
		})
		var co ContextOutput
		if err := json.Unmarshal([]byte(out), &co); err != nil {
			t.Fatalf("invalid JSON: %v\n%s", err, out)
		}
		if co.Worktree.Layout {
			t.Errorf("worktree.layout = true, want false for non-worktree repo")
		}
		if co.Worktree.Root != "" {
			t.Errorf("worktree.root = %q, want empty", co.Worktree.Root)
		}
		// Defaults are always exposed even when inert.
		if co.Worktree.BaseBranch != config.DefaultBaseBranch || co.Worktree.BranchPrefix != config.DefaultBranchPrefix {
			t.Errorf("defaults = (%q, %q), want (%q, %q)",
				co.Worktree.BaseBranch, co.Worktree.BranchPrefix, config.DefaultBaseBranch, config.DefaultBranchPrefix)
		}
	})

	t.Run("worktree layout populated with overrides", func(t *testing.T) {
		root := t.TempDir()
		cfg := &config.Config{
			SchemaVersion: config.SchemaVersion,
			SpecPath:      "code/[branch]/.vector/specs/<slug>/",
			SpecFilename:  "spec.md",
			SpecStore:     config.StoreConvention,
			Source:        config.SourceDefault,
			BaseBranch:    "develop",
			BranchPrefix:  "spec/",
		}
		if err := config.Write(root, cfg); err != nil {
			t.Fatalf("write config: %v", err)
		}
		writeContextFile(t, root, "go.mod", "module example.com/x\n\ngo 1.26\n")
		out := captureStdout(t, func() error {
			return runContext([]string{"--repo-root", root, "--json"})
		})
		var co ContextOutput
		if err := json.Unmarshal([]byte(out), &co); err != nil {
			t.Fatalf("invalid JSON: %v\n%s", err, out)
		}
		if !co.Worktree.Layout {
			t.Error("worktree.layout = false, want true for [branch] layout")
		}
		if co.Worktree.Root != "code" {
			t.Errorf("worktree.root = %q, want %q", co.Worktree.Root, "code")
		}
		if co.Worktree.BaseBranch != "develop" || co.Worktree.BranchPrefix != "spec/" {
			t.Errorf("override = (%q, %q), want (develop, spec/)", co.Worktree.BaseBranch, co.Worktree.BranchPrefix)
		}
	})
}

// TestContextShipBlock verifies the ship block is present only when the repo
// configured `ship`, with the base-branch fallback applied.
func TestContextShipBlock(t *testing.T) {
	// Absent by default (no ship config).
	root := seedContextRepo(t)
	out := captureStdout(t, func() error {
		return runContext([]string{"--repo-root", root, "--json"})
	})
	var co ContextOutput
	if err := json.Unmarshal([]byte(out), &co); err != nil {
		t.Fatalf("output not valid JSON: %v\n%s", err, out)
	}
	if co.Ship != nil {
		t.Errorf("ship should be absent without a ship config, got %+v", co.Ship)
	}

	// Present when configured; empty base branch falls back to the worktree default.
	cfg := config.Resolve(root)
	cfg.Ship = &config.ShipConfig{Mode: config.ShipModeAuto, ExcludeGlobs: []string{"dist/"}}
	if err := config.Write(root, cfg); err != nil {
		t.Fatalf("write config: %v", err)
	}
	out = captureStdout(t, func() error {
		return runContext([]string{"--repo-root", root, "--json"})
	})
	if err := json.Unmarshal([]byte(out), &co); err != nil {
		t.Fatalf("output not valid JSON: %v\n%s", err, out)
	}
	if co.Ship == nil {
		t.Fatal("ship should be present when configured")
	}
	if co.Ship.Mode != "auto" {
		t.Errorf("ship.mode = %q, want auto", co.Ship.Mode)
	}
	if co.Ship.BaseBranch != co.Worktree.BaseBranch {
		t.Errorf("ship.baseBranch = %q, want worktree fallback %q", co.Ship.BaseBranch, co.Worktree.BaseBranch)
	}
	if !co.Ship.Draft {
		t.Error("ship.draft should default to true")
	}
	// ExcludeGlobs folds in the static default ahead of the configured extra.
	if len(co.Ship.ExcludeGlobs) != 2 || co.Ship.ExcludeGlobs[0] != "openspec/" || co.Ship.ExcludeGlobs[1] != "dist/" {
		t.Errorf("ship.excludeGlobs = %v, want [openspec/ dist/]", co.Ship.ExcludeGlobs)
	}
}

// TestContextUpdateOmittedInDev: every test runs as "dev", so `update` is absent
// and the golden fixtures stay byte-identical.
func TestContextUpdateOmittedInDev(t *testing.T) {
	root := seedContextRepo(t)
	out := captureStdout(t, func() error {
		return runContext([]string{"--repo-root", root, "--json"})
	})
	var fields map[string]json.RawMessage
	if err := json.Unmarshal([]byte(out), &fields); err != nil {
		t.Fatalf("invalid JSON: %v", err)
	}
	if _, ok := fields["update"]; ok {
		t.Errorf("update must be omitted in dev: %s", out)
	}
}

// TestContextUpdateFromRootHook: a released build with an available update
// surfaces it through the context stored by the root hook (no second check).
func TestContextUpdateFromRootHook(t *testing.T) {
	root := seedContextRepo(t)
	checks := 0
	stubUpdateCheck(t, "1.0.0", func(string) *updatecheck.Result {
		checks++
		return &updatecheck.Result{Available: true, Current: "v1.0.0", Latest: "v1.1.0"}
	})
	var out string
	captureStderr(t, func() {
		out = captureStdout(t, func() error {
			if code := dispatch([]string{"context", "--repo-root", root, "--json"}); code != 0 {
				t.Errorf("exit = %d", code)
			}
			return nil
		})
	})
	var co ContextOutput
	if err := json.Unmarshal([]byte(out), &co); err != nil {
		t.Fatalf("stdout is not pure JSON: %v\n%s", err, out)
	}
	want := UpdateInfo{Available: true, Current: "v1.0.0", Latest: "v1.1.0"}
	if co.Update == nil || *co.Update != want {
		t.Errorf("update = %+v, want %+v", co.Update, want)
	}
	if checks != 1 {
		t.Errorf("update check ran %d times, want exactly 1", checks)
	}
}

// TestContextUpdateOmittedWhenCurrent: a released build that is up to date omits
// the field.
func TestContextUpdateOmittedWhenCurrent(t *testing.T) {
	root := seedContextRepo(t)
	stubUpdateCheck(t, "1.1.0", func(string) *updatecheck.Result {
		return &updatecheck.Result{Available: false, Current: "v1.1.0", Latest: "v1.1.0"}
	})
	out := captureStdout(t, func() error {
		dispatch([]string{"context", "--repo-root", root, "--json"})
		return nil
	})
	if strings.Contains(out, `"update"`) {
		t.Errorf("update must be omitted when up to date: %s", out)
	}
}
