package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/mariocampbell/vector/internal/config"
)

// seedContextRepo writes a minimal config + Go/Node repo so runContext can run.
func seedContextRepo(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	if err := config.Write(root, config.Resolve(root)); err != nil {
		t.Fatalf("write config: %v", err)
	}
	// Root go.mod so DetectBuildCmds (root-only) resolves Go build/test commands.
	writeContextFile(t, root, "go.mod", "module example.com/x\n\ngo 1.26\n")
	writeContextFile(t, root, "cmd/app/main.go", "package main\nfunc main() {}\n")
	writeContextFile(t, root, "web/package.json", `{"name":"web","main":"src/main.tsx"}`)
	writeContextFile(t, root, "web/src/main.tsx", "export {}\n")
	return root
}

func writeContextFile(t *testing.T, root, rel, content string) {
	t.Helper()
	abs := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(abs), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(abs, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", rel, err)
	}
}

// TestContextBackwardCompat verifies the no-flag output keeps the existing
// ContextOutput shape and gains only the additive intel field.
func TestContextBackwardCompat(t *testing.T) {
	root := seedContextRepo(t)
	out := captureStdout(t, func() error {
		return runContext([]string{"--repo-root", root, "--json"})
	})
	var co ContextOutput
	if err := json.Unmarshal([]byte(out), &co); err != nil {
		t.Fatalf("output not valid ContextOutput JSON: %v\n%s", err, out)
	}
	if co.Intel == nil {
		t.Fatal("expected additive intel field to be populated")
	}
	if co.Intel.Stack.Runtime.Name != "go" {
		t.Errorf("intel.stack.runtime = %+v, want go", co.Intel.Stack.Runtime)
	}
	// The cache must have been generated on read.
	if _, err := os.Stat(filepath.Join(root, ".vector", "cache", "fingerprints.json")); err != nil {
		t.Errorf("fingerprints.json not generated by vector context: %v", err)
	}
}

// TestContextForProjection covers the --for slices per tier and the unknown-command error.
func TestContextForProjection(t *testing.T) {
	root := seedContextRepo(t)

	t.Run("lazy tier (raw)", func(t *testing.T) {
		out := captureStdout(t, func() error {
			return runContext([]string{"--repo-root", root, "--json", "--for", "raw"})
		})
		var cs ContextSlice
		if err := json.Unmarshal([]byte(out), &cs); err != nil {
			t.Fatalf("invalid slice JSON: %v\n%s", err, out)
		}
		if cs.Command != "raw" || cs.Tier != "lazy-validate" {
			t.Errorf("command/tier = %s/%s, want raw/lazy-validate", cs.Command, cs.Tier)
		}
		if len(cs.ValidatedDomains) != 2 {
			t.Errorf("validatedDomains = %v, want [stack workspace]", cs.ValidatedDomains)
		}
		if cs.Stack == nil {
			t.Error("lazy slice missing stack summary")
		}
		if cs.BuildCmd != "" {
			t.Errorf("lazy slice should not carry buildCmd, got %q", cs.BuildCmd)
		}
	})

	t.Run("full tier (apply)", func(t *testing.T) {
		out := captureStdout(t, func() error {
			return runContext([]string{"--repo-root", root, "--json", "--for", "apply"})
		})
		var cs ContextSlice
		if err := json.Unmarshal([]byte(out), &cs); err != nil {
			t.Fatalf("invalid slice JSON: %v\n%s", err, out)
		}
		if cs.Tier != "full-validate" {
			t.Errorf("tier = %s, want full-validate", cs.Tier)
		}
		if cs.Stack == nil {
			t.Error("full slice missing stack summary")
		}
		if cs.TestCmd == "" {
			t.Error("full slice should carry testCmd (Go repo → go test)")
		}
	})

	t.Run("trust tier (status)", func(t *testing.T) {
		// Fresh root: prior subtests share `root` and would have created the cache.
		root := seedContextRepo(t)
		out := captureStdout(t, func() error {
			return runContext([]string{"--repo-root", root, "--json", "--for", "status"})
		})
		var cs ContextSlice
		if err := json.Unmarshal([]byte(out), &cs); err != nil {
			t.Fatalf("invalid slice JSON: %v\n%s", err, out)
		}
		if cs.Tier != "trust" {
			t.Errorf("tier = %s, want trust", cs.Tier)
		}
		if len(cs.ValidatedDomains) != 0 {
			t.Errorf("trust slice validatedDomains = %v, want empty", cs.ValidatedDomains)
		}
		if cs.Stack != nil || cs.ExamplePath != "" {
			t.Error("trust slice should carry no repo payload")
		}
		// Trust commands must not touch the cache.
		if _, err := os.Stat(filepath.Join(root, ".vector", "cache")); !os.IsNotExist(err) {
			t.Errorf("trust tier wrote cache dir (err=%v)", err)
		}
	})

	t.Run("unknown command errors", func(t *testing.T) {
		err := runContext([]string{"--repo-root", root, "--json", "--for", "nope"})
		if err == nil {
			t.Fatal("expected error for unknown --for command")
		}
	})
}
